version: '3.1'

services:
  
  mmnginx:
    container_name: mmnginx
    build: ./env/nginx
    ports:
      - 8081:8081
    expose:
      - 80
      - 443
    env_file:
      - ./env/nginx/.env
    depends_on:
      - mmnodejs
    tty: true
    volumes:
      - ./src:/home/www/naturalremedy/src
      - ./storage:/home/www/storage/naturalremedy
      - ./data/nginx/logs:/var/log/nginx
      - ./env/nginx/webserver/nginx.conf:/etc/nginx/nginx.conf
      - ./env/nginx/webserver/conf.d:/etc/nginx/conf.d
      - ./env/nginx/webserver/defaults:/etc/nginx/defaults
      - ./env/nginx/webserver/global:/etc/nginx/global
      - /var/run/docker.sock:/tmp/docker.sock:ro

  mmpostgres:
    build: ./env/postgres
    container_name: postgres
    env_file: env/postgres/.env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./data/postgres:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

  mmnodejs:
    build: ./env/nodejs
    container_name: nodejs
    env_file: env/nodejs/.env
    environment:
      - PORT=80
      - NODE_ENV=production
    # restart: always
    volumes:
      - ./src:/home/www/src:delegated
      - ./env:/var/env:delegated
    tty: true
    ports:
      - 3000:3000

networks:
  default:
    external:
      name: nginx-proxy